[package]
name = "n8v-blockchain"
version = "0.1.0"
authors = ["Se'khu Hadjo Gentle <micohadjo@yamasseenation.org>"]
edition = "2018"  # Use "2018" or "2021" as the edition, NOT "2024"

[dependencies]
substrate-node-template = { git = "https://github.com/substrate-developer-hub/substrate-node-template", branch = "master" }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
pallet-balances = { version = "4.0.0-dev", default-features = false }

# Dependencies for quantum-resistant cryptography
pqcrypto-dilithium = "0.7.0"

# Dependencies for Python integration
cpython = "0.5.0"

# Dependencies for testing
sp-runtime = { version = "4.0.0-dev", default-features = false, features = ["std"] }
sp-io = { version = "4.0.0-dev", default-features = false, features = ["std"] }
