[package]
name = "n8v-blockchain"
version = "0.1.0"
authors = ["Mico Se'khu Hadjo Gentle <micohadjo@yamasseenation.org>"]
edition = "2018"  # Usually, the edition is either "2015" or "2018". If you need to use "2021", that's also supported in Rust, but "2024" is not valid.

[dependencies]
substrate-node-template = { git = "https://github.com/substrate-developer-hub/substrate-node-template", branch = "master" }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
pallet-balances = { version = "4.0.0-dev", default-features = false }

# Dependencies for quantum-resistant cryptography
pqcrypto-dilithium = "0.7.0"

# Dependencies for Python integration
cpython = "0.5.0"

# Dependencies for testing
sp-runtime = { version = "4.0.0-dev", default-features = false, features = ["std"] }
sp-io = { version = "4.0.0-dev", default-features = false, features = ["std"] }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "sp-runtime/std",
    "sp-io/std"
]

