
[package]
name = "n8v-blockchain"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["std"] }
sha2 = { version = "0.9.8", features = ["std"] }
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = { version = "1.0", features = ["std"] }
libp2p = { version = "0.54.1", default-features = false, features = ["std"] }
tokio = { version = "1.40.0", features = ["full"] }
hex = { version = "0.4", features = ["std"] }
once_cell = { version = "1.5", features = ["std"] }
log = { version = "0.4", features = ["std"] }
pretty_env_logger = "0.4"
pqcrypto-dilithium = { version = "0.5.0", features = ["std"] }
cpython = { version = "0.5.2", features = ["extension-module"], default-features = false }
frame-support = { version = "4.0.0", default-features = false, features = ["std"] }
frame-system = { version = "4.0.0", default-features = false, features = ["std"] }
schnorrkel = { version = "0.11.4", features = ["std"] }

[features]
default = ["std"]
std = [
    "chrono/std",
    "sha2/std",
    "serde/std",
    "serde_json/std",
    "hex/std",
    "once_cell/std",
    "log/std",
    "schnorrkel/std",
    "pqcrypto-dilithium/std",
    "frame-support/std",
    "frame-system/std"
]

[[bin]]
name = "n8v-blockchain-node"
path = "node/src/main.rs"

[lib]
name = "n8v_blockchain"
path = "pallets/template/src/lib.rs"

[dev-dependencies]
sp-core = { version = "6.0.0" }
