[package]
name = "n8v-blockchain"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4"
sha2 = "0.9.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libp2p = { version = "0.54.1" }  # Use the latest compatible version of libp2p
tokio = { version = "1.40.0" }  # Specify the version without std feature
hex = "0.4"
once_cell = "1.5"
log = "0.4"
pretty_env_logger = "0.4"
schnorrkel = "0.11.4"
pqcrypto-dilithium = "0.5.0"
cpython = "0.5.2"  # Ensure no std feature conflicts

[features]
default = ["std"]
std = [
    "chrono/std",
    "sha2/std",
    "serde/std",
    "serde_json/std",
    "libp2p/std",
    "hex/std",
    "once_cell/std",
    "log/std",
    "schnorrkel/std",
    "pqcrypto-dilithium/std"
    # Removed tokio/std and cpython/std to avoid conflicts
]

[[bin]]
name = "n8v-blockchain-node"
path = "node/src/main.rs"

[lib]
name = "n8v_blockchain"
path = "pallets/template/src/lib.rs"
