[package]
name = "n8v-blockchain"
version = "0.1.0"
authors = ["Se'khu Hadjo Gentle <micohadjo@yamasseenation.org>"]
edition = "2018"  # Use "2018" or "2021" as the edition

[dependencies]
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false, features = ["std"] }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false, features = ["std"] }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }

# Dependencies for quantum-resistant cryptography
pqcrypto-dilithium = "0.5.0"

# Dependencies for Python integration
cpython = "0.5.0"

# Dependencies for schnorrkel, ensuring only one version is used
schnorrkel = { version = "0.9.1", default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-io/std",
    "sp-application-crypto/std",
    "schnorrkel/std"
]

[[bin]]
name = "n8v-blockchain-node"
path = "node/src/main.rs"

[lib]
name = "n8v_blockchain"
path = "pallets/template/src/lib.rs"

[patch.crates-io]
schnorrkel = { git = "https://github.com/w3f/schnorrkel", branch = "master" }
