[package]
name = "n8v-blockchain"
version = "0.1.0"
authors = ["Se'khu Hadjo Gentle <micohadjo@yamasseenation.org>"]
edition = "2018"  # Use "2018" or "2021" as the edition

[dependencies]
substrate-frame = { git = "https://github.com/paritytech/substrate", package = "frame-support", branch = "polkadot-v0.9.37" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }

# Dependencies for quantum-resistant cryptography
pqcrypto-dilithium = "0.5.0"

# Dependencies for Python integration
cpython = "0.5.0"

# Dependencies for testing
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false, features = ["std"] }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false, features = ["std"] }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "sp-runtime/std",
    "sp-io/std"
]

# Specify the binary target
[[bin]]
name = "n8v-blockchain-node"
path
