[package]
name = "n8v-blockchain"
version = "0.2.0"
edition = "2021"

[dependencies]
# Ensure all major dependencies are pinned to the same major version.
schnorrkel = { version = "0.11.4", features = ["std"] }
sp-core = { version = "8.0.0", features = ["std"] }
sp-runtime = { version = "8.0.0", features = ["std"] }
sp-io = { version = "8.0.0", default-features = false }
frame-support = { version = "4.0.0", default-features = false, features = ["std"] }
frame-system = { version = "4.0.0", default-features = false, features = ["std"] }
serde = "1.0"
serde_json = "1.0"
libp2p = { version = "0.54.1", default-features = false }
tokio = { version = "1.40.0", features = ["full"] }
hex = { version = "0.4", features = ["std"] }
once_cell = { version = "1.5", features = ["std"] }
log = { version = "0.4", features = ["std"] }
pretty_env_logger = "0.4"
pqcrypto-dilithium = { version = "0.5.0", features = ["std"] }
cpython = { version = "0.5.2", features = ["extension-module"], default-features = false }

[features]
default = ["std"]
std = [
    "chrono/std",
    "sha2/std",
    "serde/std",
    "serde_json/std",
    "hex/std",
    "once_cell/std",
    "log/std",
    "schnorrkel/std",
    "pqcrypto-dilithium/std",
    "frame-support/std",
    "frame-system/std"
]

[[bin]]
name = "n8v-blockchain-node"
path = "node/src/main.rs"

[dev-dependencies]
sp-core = { version = "8.0.0" }
